robots:
  ur20:
    mount_point:
      x: -0.11313635
      y: 1.00151851
      z: -0.12626616
      ax: 0.00329241
      ay: -0.00478014
      az: -0.66257742
      w: 0.74897094
    payload_configurations:
      default:
        mass: 1.46
        cog:
          x: -0.015
          y: 0.014
          z: 0.016
      sander:
        mass: 3.4
        cog:
          x: -0.003
          y: 0.007
          z: 0.056
    tool0_transforms:
      tc_hook:
        y: -0.046
        z: 0.03600
        ax: 1.0
        ay: -1.0
        az: 0.0
        w: 0.0
      tc_master:
        ax: 1.0
        ay: -1.0
        az: 0.0
        w: 0.0
      tc_connector:
        z: 0.04055
        ax: 1.0
        ay: -1.0
        az: 0.0
        w: 0.0
      calibration_tool:
        z: 0.10980
        ax: 1.0
        ay: -1.0
        az: 0.0
        w: 0.0
  nex10:
    mount_point:
      x: -0.15246845
      y: -0.71046442
      z: -0.1096908
      ax: 0.00443839
      ay: -0.00516392
      az: 0.70141325
      w: 0.7127223
    tool0_transforms:
      tc_hook:
        y: -0.046
        z: 0.060945
        ax: 1.0
        ay: -1.0
        az: 0.0
        w: 0.0
      tc_master:
        ax: 1.0
        ay: -1.0
        az: 0.0
        w: 0.0
      tc_connector:
        z: 0.065495
        ax: 1.0
        ay: -1.0
        az: 0.0
        w: 0.0
      calibration_tool:
        z: 0.1345
        ax: 1.0
        ay: -1.0
        az: 0.0
        w: 0.0
  panda:
    mount_point:
      x: 1.10
      y: 0.0
      z: -0.74
      ax: 0.00
      ay: 0.00
      az: 0.00
      w: 1.00

trays:
  tray_1:
    references:
      ur20:
        x: 1.30091469
        y: -0.71117655
        z: 0.43953399
        ax: 0.00391792
        ay: -0.00327818
        az: -0.75022564
        w: 0.66116215
      nex10:
        x: 0.31428222
        y: 0.50471749
        z: 0.4132308
        ax: -0.00204716
        ay: 0.0014461
        az: 0.71251808
        w: 0.70164928
  tray_2:
    references:
      ur20:
        x: 1.11891363
        y: -0.68807056
        z: 0.43969141
        ax: 0.00392996
        ay: -0.00329911
        az: -0.75022495
        w: 0.66116276
      nex10: 
        x: 0.49797169
        y: 0.51208398
        z: 0.41243768
        ax: -0.00178403
        ay: 0.00143909
        az: 0.71232968
        w: 0.70184127
  tray_3:
    references:
      ur20:
        x: 0.92054373
        y: -0.66218199
        z: 0.43956369
        ax: 0.00392772
        ay: -0.00328177
        az: -0.75022815
        w: 0.66115923
      nex10: 
        x: 0.69791759
        y: 0.51903821
        z: 0.4116181
        ax: -0.00176855
        ay: 0.00143193
        az: 0.71235429
        w: 0.70181635

tools:
  sander:
    location: tray
    tray_name: tray_1
    child_transforms:
      sander_tooltip:
        z: -0.148005
  grinder:
    location: tray
    tray_name: tray_2
    child_transforms:
      grinder_tooltip:
        y: 0.11228
        z: -0.127948
  gelsight_vision:
    location: tray
    tray_name: tray_3
    child_transforms:
      gelsight_tooltip:
        z: -0.1144
      camera_focus:
        x: 0.045
        z: -0.234

